//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticktok_demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class calender
    {
        public System.Guid calender_id { get; set; }
        public Nullable<int> calender_year { get; set; }
        public Nullable<int> calender_month { get; set; }
        public Nullable<System.DateTime> calender_week_01_start_date { get; set; }
        public Nullable<System.DateTime> calender_week_01_end_date { get; set; }
        public Nullable<System.DateTime> calender_week_02_start_date { get; set; }
        public Nullable<System.DateTime> calender_week_02_end_date { get; set; }
        public Nullable<System.DateTime> calender_week_03_start_date { get; set; }
        public Nullable<System.DateTime> calender_week_03_end_date { get; set; }
        public Nullable<System.DateTime> calender_week_04_start_date { get; set; }
        public Nullable<System.DateTime> calender_week_04_end_date { get; set; }
        public Nullable<System.Guid> company_id { get; set; }
        public Nullable<System.Guid> holiday_id { get; set; }
        public Nullable<System.Guid> country_id { get; set; }
        public Nullable<int> num_working_days { get; set; }
    
        public virtual company company { get; set; }
        public virtual country country { get; set; }
        public virtual holiday holiday { get; set; }
    }
}
