//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticktok_demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_contact
    {
        public System.Guid emp_cont_id { get; set; }
        public string emp_address_line_01 { get; set; }
        public string emp_address_line_02 { get; set; }
        public string emp_address_city { get; set; }
        public string emp_address_postalcode { get; set; }
        public string emp_address_st_or_pr { get; set; }
        public string emp_phone_01 { get; set; }
        public string emp_phone_02 { get; set; }
        public Nullable<System.Guid> country_id { get; set; }
        public Nullable<System.Guid> employee_id { get; set; }
    
        public virtual country country { get; set; }
        public virtual employee employee { get; set; }
    }
}
