//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticktok_demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.employee_contact = new HashSet<employee_contact>();
            this.leave_employee = new HashSet<leave_employee>();
            this.leave_employee1 = new HashSet<leave_employee>();
            this.tracking_sheet = new HashSet<tracking_sheet>();
        }
    
        public System.Guid emp_id { get; set; }
        public string emp_first_name { get; set; }
        public string emp_last_name { get; set; }
        public Nullable<System.Guid> comp_id { get; set; }
        public Nullable<System.Guid> holiday_id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.Guid> job_des_id { get; set; }
        public string pic { get; set; }
    
        public virtual company company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_contact> employee_contact { get; set; }
        public virtual holiday holiday { get; set; }
        public virtual job_description job_description { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leave_employee> leave_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leave_employee> leave_employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tracking_sheet> tracking_sheet { get; set; }
    }
}
