//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticktok_demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class leave_employee
    {
        public System.Guid leave_emp_id { get; set; }
        public Nullable<System.Guid> leave_group_id { get; set; }
        public Nullable<System.DateTime> leave_start_date { get; set; }
        public Nullable<System.DateTime> leave_end_date { get; set; }
        public string leave_reason { get; set; }
        public string leave_status { get; set; }
        public Nullable<System.Guid> approve_by_emp_id { get; set; }
        public Nullable<System.Guid> employee_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
