//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticktok_demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public System.Guid task_id { get; set; }
        public string task_name { get; set; }
        public Nullable<System.TimeSpan> task_start_time { get; set; }
        public Nullable<System.TimeSpan> task_end_time { get; set; }
        public string task_description { get; set; }
        public Nullable<System.Guid> tracking_sheet_id { get; set; }
        public Nullable<System.Guid> project_id { get; set; }
    
        public virtual project project { get; set; }
        public virtual tracking_sheet tracking_sheet { get; set; }
    }
}
