//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticktok_demo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tickEntities : DbContext
    {
        public tickEntities()
            : base("name=tickEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<calender> calenders { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employee_contact> employee_contact { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<job_description> job_description { get; set; }
        public virtual DbSet<leave_group> leave_group { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tracking_sheet> tracking_sheet { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<leave_employee> leave_employee { get; set; }
        public virtual DbSet<user_roles> user_roles { get; set; }
        public virtual DbSet<user_role_reference> user_role_reference { get; set; }
    }
}
